### ISSUE TITLE
Switching default branches to `main`

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1696]
We've recently agreed to changing our default branch from "master" to "main".

### Impacted Repos

By looking at the `sinatra` org quickly, I've determined the following projects may change:

- [x] [sinatra](https://github.com/sinatra/sinatra)
- [x] [mustermann](https://github.com/sinatra/mustermann)
- [x] [mustermann-sinatra-extension](https://github.com/sinatra/mustermann-sinatra-extension) (archived)
- [x] [sinatra-book](https://github.com/sinatra/sinatra-book)
- [x] [sinatra.github.com](https://github.com/sinatra/sinatra.github.com): I'm guessing this _will be fine_ with GH Pages
- [x] [sinatra-recipes](https://github.com/sinatra/sinatra-recipes)

I left out a few repos which I've went through and marked as deprecated / read-only, I'm not sure we should worry about changing the default branch for these. :shrug:

### TODO

I'm fairly sure switching the branch should be seamless, but I'm not sure if there is any tooling we need to be aware of, or documentation we should update.

**Comment by epergo** [comment]
What would happen with the `master` branch once we switch to `main`? Will it be dropped or will it be in sync with `main` to avoid breaking people's builds? (which will only happen if they are pointing to `master` ofc)

Asking because if we are planning to completely drop `master`, could we drop `stable` branch too? I think it's not referenced in docs anymore and the Sinatra version it contains is `1.4.8`, we should avoid users installing old versions of Sinatra.

(Sorry for the offtopic but opening a new issue seemed too much?)

**Comment by dentarg** [comment]
@epergo See https://github.com/github/renaming#renaming-existing-branches

**Comment by epergo** [comment]
Thanks for the link @dentarg! I thought the process of renaming the `master` branch was a series of manual steps and that one of them was manually deleting the branch.

Then the `stable` branch _issue_ is a completely different thing.

**Comment by zzak** [comment]
@epergo No these are good concerns, and why I wanted to open this ticket before doing any work.

I've been a bit removed from Sinatra for some time now, so I want to make sure this change doesn't impact anyone's workflow but also we have a place to discuss these types of issues.

**Comment by boardfish** [comment]
AFAIK [this line](https://github.com/sinatra/sinatra/blob/master/.github/workflows/test.yml#L13) would need to be changed so that this workflow is run against `main`. Assuming this repo only runs CI and other automations via GitHub Actions, no other action would be necessary besides purging `master` from the docs too, if it's present at all.

**Comment by jkowens** [comment]
I think we can plan on moving forward with this after the 3.0 release.

**Comment by dentarg** [comment]
I think we should get on with this, here's an PR that update the references in this repo: https://github.com/sinatra/sinatra/pull/1894

**Comment by dentarg** [comment]
I don't have access to settings on https://github.com/sinatra/mustermann-sinatra-extension @epergo @zzak but I will do the others now.

**Comment by zzak** [comment]
@dentarg I've given `@sinatra/team-sinatra` admin access to that repo. Since that gem is deprecated, should it be archived as read-only?

**Comment by dentarg** [comment]
Yes, that makes sense. I archived it now. I didn't change the branch name.
